language: php
dist: precise
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
after_script:
  - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/155f53c8074ea0a9073e
    on_success: always
    on_failure: always
    on_start: never
